[paths]
team_game_logs = "./data/raw/team_game_logs"
boxscore_traditional = "./data/raw/boxscore_traditional"
boxscore_advanced = "./data/raw/boxscore_advanced"

[params]
season = ["2022-23", "2023-24"]
season_type = ["Regular Season", "Playoffs"]
